// Generated by CoffeeScript 2.3.2
(function() {
  'use strict';
  var $, CND, FS, PATH, PD, TEMPLATES, alert, assign, async, badge, debug, help, info, jr, page_html_path, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = '明快打字机/APP';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  PATH = require('path');

  FS = require('fs');

  TEMPLATES = require('./templates');

  ({jr} = CND);

  assign = Object.assign;

  //...........................................................................................................
  PD = require('pipedreams');

  ({$, async} = PD);

  //...........................................................................................................
  page_html_path = PATH.resolve(PATH.join(__dirname, '../public/main.html'));

  // S                         = require './settings'

  //-----------------------------------------------------------------------------------------------------------
  this.write_page_source = function() {
    /* Write out the HTML of the main page; this is strictly only needed when template has changed, which we
    maybe should detect in the future: */
    var page_source;
    page_source = TEMPLATES.main_2();
    // page_source = TEMPLATES.minimal()
    FS.writeFileSync(page_html_path, page_source);
    return help(`updated page source written to ${rpr(PATH.relative(process.cwd(), page_html_path))}`);
  };

  this.write_page_source();

}).call(this);

//# sourceMappingURL=main.js.map
